spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_learn
    username:
    password:
mybatis:
  mapper-locations: classpath:mapper/*.xml